### ISSUE TITLE
[Akai Fire] Step copy crashes the extension in Bitwig 5.1.2

### ISSUE THREAD

**Issue by mcristi** [ericahrens/rhbitwig#16]
Copying a step does not work: it produces the following error. 
```
Parameter insertDuration (=0.0) must be > 0.0
vGz: Parameter insertDuration (=0.0) must be > 0.0
    at com.bitwig.flt.control_surface.proxy.ControlSurfaceObject.greaterThan(SourceFile:451)
    at com.bitwig.flt.control_surface.proxy.ClipProxy.setStepCommon(SourceFile:469)
    at com.bitwig.flt.control_surface.proxy.ClipProxy.setStep(SourceFile:443)
    at com.bitwig.flt.control_surface.proxy.DelegatingClipProxy.setStep(SourceFile:146)
    at com.akai.fire.sequence.PadHandler.executeCopy(PadHandler.java:145)
    at com.akai.fire.sequence.PadHandler.executePadSelection(PadHandler.java:191)
    at com.akai.fire.sequence.PadContainer.handlePadSelection(PadContainer.java:102)
    at com.akai.fire.sequence.PadContainer.lambda$new$0(PadContainer.java:62)
```
This happens with the latest `rhbitwig` from `api-18` and Bitwig 5.1.2.

The clip copy works as expected. 

Thanks and a Happy New Year! 🎆 🎉

**Comment by mcristi** [comment]
@ericahrens I have tried to debug the issue, but it looks like a regression in the Bitwig API. Is there any chance you can forward this to the development team?

**Comment by ericahrens** [comment]
I will try look at this in the next few days. Just so super busy with other stuff.

**Comment by userdsp** [comment]
I have the same error

**Comment by userdsp** [comment]
I have the same error even with the Master branch

The master branch is compiling file with name HawtinExtensionsBw4.bwextension not HawtinExtensionsBw5.bwextension 
is this normal?

**Comment by userdsp** [comment]
https://github.com/userdsp/rhbitwig/tree/codespace-friendly-giggle-5wgvqgp9526pv

I fixed it. Now it's working perfectly also with Bitwig 6
